---
name: test

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  unittest:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Run unittest
        run: make check
