---
name: test

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  black:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
    steps:
      - name: Update APT cache
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install --no-install-recommends --yes black
      - uses: actions/checkout@v6
      - name: Run black check
        run: make black

  isort:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
    steps:
      - name: Update APT cache
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install --no-install-recommends --yes isort
      - uses: actions/checkout@v6
      - name: Run isort check
        run: make isort

  mypy:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
    steps:
      - name: Update APT cache
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install --no-install-recommends --yes mypy
      - uses: actions/checkout@v6
      - name: Run mypy check
        run: make mypy

  pylint:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
    steps:
      - name: Update APT cache
        run: sudo apt-get update
      - name: Install dependencies
        run: >
          sudo apt-get install --no-install-recommends --yes
          pylint python3-jinja2
      - uses: actions/checkout@v6
      - name: Run pylint check
        run: make pylint

  ruff:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v4.0.0

  unittest:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
    steps:
      - name: Update APT cache
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install --no-install-recommends --yes python3-jinja2
      - uses: actions/checkout@v6
      - name: Run unittest
        run: make check
